In [1]:
# STEP 1: Importing Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# STEP 2: Importing Dataset

In [4]:
dataset=pd.read_csv('kidney_disease.csv')
dataset

id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent   
1      1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent   
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent   
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present   
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent   
..   ...   ...   ...    ...  ...  ...     ...       ...         ...   
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent   

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no   
1    notpresent  ...   38  6000  NaN   no   no   no  good   no   no   
2    notpresent  ...   31  7500  NaN   no  yes   no  poor   no  yes   
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes   
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no   
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no   
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no   
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no   
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no   
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no   

    classification  
0              ckd  
1              ckd  
2              ckd  
3              ckd  
4              ckd  
..             ...  
395         notckd  
396         notckd  
397         notckd  
398         notckd  
399         notckd  

[400 rows x 26 columns]

In [5]:
# STEP 4: Taking Care Of Missing Data

In [6]:
dataset.fillna(dataset.mean(),inplace=True)

In [7]:
dataset.isnull().any()

id                False
age               False
bp                False
sg                False
al                False
su                False
rbc                True
pc                 True
pcc                True
ba                 True
bgr               False
bu                False
sc                False
sod               False
pot               False
hemo              False
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [8]:
dataset['rbc'].value_counts()

normal      201
abnormal     47
Name: rbc, dtype: int64

In [9]:
dataset['rbc'].fillna('normal',inplace=True)

In [10]:
dataset['pc'].value_counts()

normal      259
abnormal     76
Name: pc, dtype: int64

In [11]:
dataset['pc'].fillna('normal',inplace=True)

In [12]:
dataset['pcc'].value_counts()

notpresent    354
present        42
Name: pcc, dtype: int64

In [13]:
dataset['pcc'].fillna('notpresent',inplace=True)

In [14]:
dataset['pcc'].value_counts()

notpresent    358
present        42
Name: pcc, dtype: int64

In [15]:
dataset['ba'].value_counts()

notpresent    374
present        22
Name: ba, dtype: int64

In [16]:
dataset['ba'].fillna('notpresent',inplace=True)

In [17]:
dataset['ba'].value_counts()

notpresent    378
present        22
Name: ba, dtype: int64

In [18]:
dataset['pcv'].value_counts()

41      21
52      21
44      19
48      19
40      16
43      14
42      13
45      13
32      12
28      12
50      12
33      12
36      12
34      11
37      11
35       9
46       9
29       9
30       9
31       8
24       7
39       7
26       6
38       5
54       4
49       4
51       4
47       4
53       4
22       3
25       3
27       3
23       2
19       2
20       1
15       1
18       1
9        1
16       1
17       1
21       1
\t?      1
14       1
\t43     1
Name: pcv, dtype: int64

In [19]:
dataset['pcv'].fillna('52',inplace=True)

In [20]:
dataset['pcv'].value_counts()

52      91
41      21
44      19
48      19
40      16
43      14
42      13
45      13
32      12
28      12
50      12
33      12
36      12
34      11
37      11
35       9
46       9
29       9
30       9
31       8
24       7
39       7
26       6
38       5
54       4
49       4
51       4
47       4
53       4
22       3
25       3
27       3
23       2
19       2
20       1
15       1
18       1
9        1
16       1
17       1
21       1
\t?      1
14       1
\t43     1
Name: pcv, dtype: int64

In [21]:
dataset[['pcv']] = dataset[['pcv']].replace('\t43','52')

In [22]:
dataset['pcv'].value_counts()

52     92
41     21
44     19
48     19
40     16
43     14
42     13
45     13
32     12
28     12
50     12
33     12
36     12
34     11
37     11
30      9
29      9
35      9
46      9
31      8
39      7
24      7
26      6
38      5
53      4
49      4
51      4
54      4
47      4
25      3
27      3
22      3
19      2
23      2
\t?     1
14      1
18      1
15      1
20      1
16      1
21      1
9       1
17      1
Name: pcv, dtype: int64

In [23]:
dataset[['pcv']] = dataset[['pcv']].replace('\t?','52')

In [24]:
dataset['pcv'].value_counts()

52    93
41    21
48    19
44    19
40    16
43    14
45    13
42    13
32    12
50    12
33    12
28    12
36    12
34    11
37    11
29     9
30     9
35     9
46     9
31     8
24     7
39     7
26     6
38     5
51     4
54     4
47     4
49     4
53     4
25     3
27     3
22     3
19     2
23     2
16     1
20     1
15     1
14     1
18     1
21     1
9      1
17     1
Name: pcv, dtype: int64

In [25]:
dataset['wc'].value_counts()

9800      11
6700      10
9200       9
7200       9
9600       9
          ..
5900       1
12200      1
\t8400     1
14900      1
4900       1
Name: wc, Length: 92, dtype: int64

In [26]:
dataset['wc'].fillna('9800',inplace=True)

In [27]:
dataset['wc'].value_counts()

9800      116
6700       10
9200        9
7200        9
9600        9
         ... 
5900        1
12200       1
\t8400      1
14900       1
4900        1
Name: wc, Length: 92, dtype: int64

In [28]:
dataset[['wc']] = dataset[['wc']].replace('\t9800','9800')

In [29]:
dataset['wc'].value_counts()

9800      116
6700       10
9200        9
7200        9
9600        9
         ... 
5900        1
12200       1
\t8400      1
14900       1
4900        1
Name: wc, Length: 92, dtype: int64

In [30]:
dataset['rc'].value_counts()

5.2    18
4.5    16
4.9    14
4.7    11
4.8    10
3.9    10
3.4     9
4.6     9
6.1     8
5.9     8
3.7     8
5.0     8
5.5     8
5.3     7
5.8     7
3.8     7
5.4     7
4.3     6
4.2     6
5.6     6
6.5     5
6.2     5
6.4     5
4.4     5
5.7     5
4.1     5
5.1     5
3.2     5
3.6     4
6.3     4
6.0     4
3.3     3
4.0     3
4       3
3.5     3
3.0     2
5       2
2.8     2
2.9     2
2.6     2
2.1     2
3.1     2
2.7     2
2.5     2
2.4     1
3       1
\t?     1
2.3     1
8.0     1
Name: rc, dtype: int64

In [31]:
dataset['rc'].fillna('5.2',inplace=True)

In [32]:
dataset[['rc']] = dataset[['rc']].replace('\t?','5.2')

In [33]:
dataset['rc'].value_counts()

5.2    149
4.5     16
4.9     14
4.7     11
4.8     10
3.9     10
3.4      9
4.6      9
6.1      8
5.9      8
3.7      8
5.0      8
5.5      8
5.3      7
5.8      7
3.8      7
5.4      7
4.3      6
4.2      6
5.6      6
6.2      5
6.4      5
4.4      5
5.7      5
6.5      5
5.1      5
3.2      5
4.1      5
3.6      4
6.0      4
6.3      4
3.3      3
4.0      3
4        3
3.5      3
3.0      2
5        2
2.8      2
2.9      2
2.6      2
2.1      2
3.1      2
2.7      2
2.5      2
3        1
2.3      1
2.4      1
8.0      1
Name: rc, dtype: int64

In [34]:
dataset['htn'].value_counts()

no     251
yes    147
Name: htn, dtype: int64

In [35]:
dataset['htn'].fillna('no',inplace=True)

In [36]:
dataset['htn'].value_counts()

no     253
yes    147
Name: htn, dtype: int64

In [37]:
dataset['dm'].value_counts()

no       258
yes      134
\tno       3
\tyes      2
 yes       1
Name: dm, dtype: int64

In [38]:
dataset['dm'].fillna('no',inplace=True)

In [39]:
dataset[['dm']] = dataset[['dm']].replace('\tyes','yes')

In [40]:
dataset[['dm']] = dataset[['dm']].replace('\tno','no')

In [41]:
dataset[['dm']] = dataset[['dm']].replace(' yes','yes')

In [42]:
dataset['dm'].value_counts()

no     263
yes    137
Name: dm, dtype: int64

In [43]:
dataset['cad'].value_counts()

no      362
yes      34
\tno      2
Name: cad, dtype: int64

In [44]:
dataset['cad'].fillna('no',inplace=True)

In [45]:
dataset[['cad']] = dataset[['cad']].replace('\tno','no')

In [46]:
dataset['dm'].value_counts()

no     263
yes    137
Name: dm, dtype: int64

In [47]:
dataset['appet'].value_counts()

good    317
poor     82
Name: appet, dtype: int64

In [48]:
dataset['appet'].fillna('good',inplace=True)

In [49]:
dataset['appet'].value_counts()

good    318
poor     82
Name: appet, dtype: int64

In [50]:
dataset['pe'].value_counts()

no     323
yes     76
Name: pe, dtype: int64

In [51]:
dataset['pe'].fillna('no',inplace=True)

In [52]:
dataset['ane'].value_counts()

no     339
yes     60
Name: ane, dtype: int64

In [53]:
dataset['ane'].fillna('no',inplace=True)

In [54]:
dataset['ane'].value_counts()

no     340
yes     60
Name: ane, dtype: int64

In [55]:
dataset['classification'].value_counts()

ckd       248
notckd    150
ckd\t       2
Name: classification, dtype: int64

In [56]:
dataset[['classification']] = dataset[['classification']].replace('ckd\t','ckd')

In [57]:
dataset['classification'].value_counts()

ckd       250
notckd    150
Name: classification, dtype: int64

In [58]:
dataset['wc'].value_counts()

9800      116
6700       10
9200        9
7200        9
9600        9
         ... 
5900        1
12200       1
\t8400      1
14900       1
4900        1
Name: wc, Length: 92, dtype: int64

In [59]:
dataset[['wc']] = dataset[['wc']].replace('\t?','9800')

In [60]:
dataset['wc'].value_counts()

9800      117
6700       10
9200        9
7200        9
9600        9
         ... 
5900        1
12200       1
\t8400      1
14900       1
4900        1
Name: wc, Length: 91, dtype: int64

In [61]:
dataset.isnull().any()

id                False
age               False
bp                False
sg                False
al                False
su                False
rbc               False
pc                False
pcc               False
ba                False
bgr               False
bu                False
sc                False
sod               False
pot               False
hemo              False
pcv               False
wc                False
rc                False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [62]:
# Independent and Dependent Variables

In [63]:
x=dataset.iloc[:,0:25].values
x

array([[0, 48.0, 80.0, ..., 'good', 'no', 'no'],
       [1, 7.0, 50.0, ..., 'good', 'no', 'no'],
       [2, 62.0, 80.0, ..., 'poor', 'no', 'yes'],
       ...,
       [397, 12.0, 80.0, ..., 'good', 'no', 'no'],
       [398, 17.0, 60.0, ..., 'good', 'no', 'no'],
       [399, 58.0, 80.0, ..., 'good', 'no', 'no']], dtype=object)

In [64]:
x.shape

(400, 25)

In [65]:
y=dataset.iloc[:,25:26].values
y

array([['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       [

In [66]:
# Step 5: Encoding Categorical text variables

In [67]:
import sklearn
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [68]:
ct=ColumnTransformer([("on",OneHotEncoder(),[6])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 1.0, 0, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 1, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 2, ..., 'poor', 'no', 'yes'],
       ...,
       [0.0, 1.0, 397, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 398, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 399, ..., 'good', 'no', 'no']], dtype=object)

In [69]:
# Removing dummy variable

In [70]:
x.shape

(400, 26)

In [71]:
x=x[:,1:]
x

array([[1.0, 0, 48.0, ..., 'good', 'no', 'no'],
       [1.0, 1, 7.0, ..., 'good', 'no', 'no'],
       [1.0, 2, 62.0, ..., 'poor', 'no', 'yes'],
       ...,
       [1.0, 397, 12.0, ..., 'good', 'no', 'no'],
       [1.0, 398, 17.0, ..., 'good', 'no', 'no'],
       [1.0, 399, 58.0, ..., 'good', 'no', 'no']], dtype=object)

In [72]:
x.shape

(400, 25)

In [73]:
ct=ColumnTransformer([("on",OneHotEncoder(),[7])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 1.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 1.0, ..., 'poor', 'no', 'yes'],
       ...,
       [0.0, 1.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 1.0, ..., 'good', 'no', 'no']], dtype=object)

In [74]:
x.shape

(400, 26)

In [75]:
x=x[:,1:]
x

array([[1.0, 1.0, 0, ..., 'good', 'no', 'no'],
       [1.0, 1.0, 1, ..., 'good', 'no', 'no'],
       [1.0, 1.0, 2, ..., 'poor', 'no', 'yes'],
       ...,
       [1.0, 1.0, 397, ..., 'good', 'no', 'no'],
       [1.0, 1.0, 398, ..., 'good', 'no', 'no'],
       [1.0, 1.0, 399, ..., 'good', 'no', 'no']], dtype=object)

In [76]:
x.shape

(400, 25)

In [77]:
ct=ColumnTransformer([("on",OneHotEncoder(),[8])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 1.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 1.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 1.0, ..., 'poor', 'no', 'yes'],
       ...,
       [1.0, 0.0, 1.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 1.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 1.0, ..., 'good', 'no', 'no']], dtype=object)

In [78]:
x.shape

(400, 26)

In [79]:
x=x[:,1:]
x

array([[0.0, 1.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 1.0, ..., 'poor', 'no', 'yes'],
       ...,
       [0.0, 1.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 1.0, ..., 'good', 'no', 'no']], dtype=object)

In [80]:
x.shape

(400, 25)

In [81]:
ct=ColumnTransformer([("on",OneHotEncoder(),[9])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'poor', 'no', 'yes'],
       ...,
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no']], dtype=object)

In [82]:
x.shape

(400, 26)

In [83]:
x=x[:,1:]
x

array([[0.0, 0.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 1.0, ..., 'poor', 'no', 'yes'],
       ...,
       [0.0, 0.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 1.0, ..., 'good', 'no', 'no']], dtype=object)

In [84]:
x.shape

(400, 25)

In [85]:
ct=ColumnTransformer([("on",OneHotEncoder(),[19])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 1.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'poor', 'no', 'yes'],
       ...,
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no']], dtype=object)

In [86]:
x.shape

(400, 26)

In [87]:
x=x[:,1:]
x

array([[1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., 'poor', 'no', 'yes'],
       ...,
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no']], dtype=object)

In [88]:
x.shape

(400, 25)

In [89]:
ct=ColumnTransformer([("on",OneHotEncoder(),[20])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[0.0, 1.0, 1.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 0.0, ..., 'poor', 'no', 'yes'],
       ...,
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no']], dtype=object)

In [90]:
x.shape

(400, 26)

In [91]:
x=x[:,1:]
x

array([[1.0, 1.0, 0.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'poor', 'no', 'yes'],
       ...,
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no']], dtype=object)

In [92]:
x.shape

(400, 25)

In [93]:
ct=ColumnTransformer([("on",OneHotEncoder(),[21])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 1.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 1.0, ..., 'poor', 'no', 'yes'],
       ...,
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., 'good', 'no', 'no']], dtype=object)

In [94]:
x.shape

(400, 26)

In [95]:
x=x[:,1:]
x

array([[0.0, 1.0, 1.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [0.0, 1.0, 0.0, ..., 'poor', 'no', 'yes'],
       ...,
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., 'good', 'no', 'no']], dtype=object)

In [96]:
x.shape

(400, 25)

In [97]:
ct=ColumnTransformer([("on",OneHotEncoder(),[22])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., '5.2', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., '5.2', 'no', 'no'],
       [0.0, 1.0, 0.0, ..., '5.2', 'no', 'yes'],
       ...,
       [1.0, 0.0, 0.0, ..., '5.4', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., '5.9', 'no', 'no'],
       [1.0, 0.0, 0.0, ..., '6.1', 'no', 'no']], dtype=object)

In [98]:
x.shape

(400, 26)

In [99]:
x=x[:,1:]
x

array([[0.0, 0.0, 1.0, ..., '5.2', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., '5.2', 'no', 'no'],
       [1.0, 0.0, 1.0, ..., '5.2', 'no', 'yes'],
       ...,
       [0.0, 0.0, 0.0, ..., '5.4', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., '5.9', 'no', 'no'],
       [0.0, 0.0, 0.0, ..., '6.1', 'no', 'no']], dtype=object)

In [100]:
x.shape

(400, 25)

In [101]:
ct=ColumnTransformer([("on",OneHotEncoder(),[23])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., '7800', '5.2', 'no'],
       [1.0, 0.0, 0.0, ..., '6000', '5.2', 'no'],
       [1.0, 0.0, 1.0, ..., '7500', '5.2', 'yes'],
       ...,
       [1.0, 0.0, 0.0, ..., '6600', '5.4', 'no'],
       [1.0, 0.0, 0.0, ..., '7200', '5.9', 'no'],
       [1.0, 0.0, 0.0, ..., '6800', '6.1', 'no']], dtype=object)

In [102]:
x.shape

(400, 26)

In [103]:
x=x[:,1:]
x

array([[0.0, 0.0, 0.0, ..., '7800', '5.2', 'no'],
       [0.0, 0.0, 0.0, ..., '6000', '5.2', 'no'],
       [0.0, 1.0, 0.0, ..., '7500', '5.2', 'yes'],
       ...,
       [0.0, 0.0, 0.0, ..., '6600', '5.4', 'no'],
       [0.0, 0.0, 0.0, ..., '7200', '5.9', 'no'],
       [0.0, 0.0, 0.0, ..., '6800', '6.1', 'no']], dtype=object)

In [104]:
x.shape

(400, 25)

In [105]:
ct=ColumnTransformer([("on",OneHotEncoder(),[24])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., '44', '7800', '5.2'],
       [1.0, 0.0, 0.0, ..., '38', '6000', '5.2'],
       [0.0, 1.0, 0.0, ..., '31', '7500', '5.2'],
       ...,
       [1.0, 0.0, 0.0, ..., '49', '6600', '5.4'],
       [1.0, 0.0, 0.0, ..., '51', '7200', '5.9'],
       [1.0, 0.0, 0.0, ..., '53', '6800', '6.1']], dtype=object)

In [106]:
x.shape

(400, 26)

In [107]:
x=x[:,1:]
x

array([[0.0, 0.0, 0.0, ..., '44', '7800', '5.2'],
       [0.0, 0.0, 0.0, ..., '38', '6000', '5.2'],
       [1.0, 0.0, 1.0, ..., '31', '7500', '5.2'],
       ...,
       [0.0, 0.0, 0.0, ..., '49', '6600', '5.4'],
       [0.0, 0.0, 0.0, ..., '51', '7200', '5.9'],
       [0.0, 0.0, 0.0, ..., '53', '6800', '6.1']], dtype=object)

In [108]:
x.shape

(400, 25)

In [109]:
# Label Encoder

In [110]:
from sklearn.preprocessing import LabelEncoder

In [111]:
y.shape

(400, 1)

In [112]:
lb=LabelEncoder()
y=lb.fit_transform(y)
y

C:\Users\Deepak\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [113]:
y.shape

(400,)

In [114]:
dataset

id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0  normal    normal  notpresent   
1      1   7.0  50.0  1.020  4.0  0.0  normal    normal  notpresent   
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent   
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present   
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent   
..   ...   ...   ...    ...  ...  ...     ...       ...         ...   
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent   

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no   
1    notpresent  ...   38  6000  5.2   no   no   no  good   no   no   
2    notpresent  ...   31  7500  5.2   no  yes   no  poor   no  yes   
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes   
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no   
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no   
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no   
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no   
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no   
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no   

    classification  
0              ckd  
1              ckd  
2              ckd  
3              ckd  
4              ckd  
..             ...  
395         notckd  
396         notckd  
397         notckd  
398         notckd  
399         notckd  

[400 rows x 26 columns]

In [115]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-0.42008403, -0.4843221 , -0.50780078, ...,  0.28878993,
        -0.37605137,  0.38052135],
       [-0.42008403, -0.4843221 , -0.50780078, ..., -0.337879  ,
        -1.06994422,  0.38052135],
       [ 2.38047614, -0.4843221 ,  1.96927621, ..., -1.06899276,
        -0.49170018,  0.38052135],
       ...,
       [-0.42008403, -0.4843221 , -0.50780078, ...,  0.81101405,
        -0.8386466 ,  0.6102701 ],
       [-0.42008403, -0.4843221 , -0.50780078, ...,  1.01990369,
        -0.60734899,  1.18464195],
       [-0.42008403, -0.4843221 , -0.50780078, ...,  1.22879334,
        -0.7615474 ,  1.4143907 ]])